sudo: required

env:
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
services:
  - docker

before_install:
  - docker pull geerlingguy/docker-${distro}-ansible:latest

script:
  - container_id=$(mktemp)

  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'
  #- 'docker exec "$(cat ${container_id})" df -h'
  - >
    docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check

notifications:
  webhooks: 
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_success: always
    on_failure: never
  email:
    on_failure: never
    on_success: never