---
- name: Get VirtualBox version
  shell: cat /home/vagrant/.vbox_version
  register: virtualbox_version

- name: Mount VirtualBox guest ISO
  become: true
  mount:
    name: /tmp/vbox
    src: "/home/vagrant/VBoxGuestAdditions_{{virtualbox_version.stdout}}.iso"
    opts: loop
    state: mounted
    fstype: iso9660

- name: Run VirtualBox guest addtions install
  become: true
  shell: sh /tmp/vbox/VBoxLinuxAdditions.run
  failed_when: false

- name: Umount VirtualBox guest additions ISO.
  become: true
  mount:
    name: /tmp/vbox
    src: "/home/vagrant/VBoxGuestAdditions_{{virtualbox_version.stdout}}.iso"
    opts: loop
    state: absent
    fstype: iso9660