---
- name: Add VMware tools repistory.
  template:
    src: vmware-tools.repo.j2
    dest: /etc/yum.repos.d/vmware-tools.repo

- name: Import VMware tools GPG keys 
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - "http://packages.vmware.com/tools/keys/VMWARE-PACKAGING-GPG-DSA-KEY.pub"
    - "http://packages.vmware.com/tools/keys/VMWARE-PACKAGING-GPG-RSA-KEY.pub"

- name: Install open-vm-tools.
  yum: "name={{ item }} state=present"
  with_items:
    - open-vm-tools

- name: Create temporary directories for VMware tools.
  file:
    path: "/tmp/{{ item }}"
    state: directory
  with_items:
    - vmfusion
    - vmfusion-archive

- command: ls -lah /home/vagrant
  register: vaglist
- debug: var=vaglist

- name: Mount VMware tools.
  mount:
    name: /tmp/vmfusion
    src: /home/vagrant/linux.iso
    fstype: iso9660
    opts: loop
    state: mounted

- name: Decompress VMware Tools installer into archive folder.
  shell: tar xzf /tmp/vmfusion/VMwareTools-*.tar.gz -C /tmp/vmfusion-archive

- name: Run the VMware tools installer.
  shell: /tmp/vmfusion-archive/vmware-tools-distrib/vmware-install.pl --default

- name: Unmount VMware tools.
  mount:
    name: /tmp/vmfusion
    src: /home/vagrant/linux.iso
    fstype: iso9660
    state: absent

- name: Remove temporary directories for VMware tools.
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - vmfusion
    - vmfusion-archive

- name: Delete VMware Tools.
  file:
    path: /home/vagrant/linux.iso
    state: absent